# Generated by Django 4.2.5 on 2024-11-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
